name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: madhead/read-java-properties@latest
        id: gradle_props
        with:
          file: gradle.properties
          all: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.gradle_props.outputs.java_version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache/remapped-mods
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive Jar
        uses: actions/upload-artifact@v4
        with:
          name: build_jar
          path: build/libs